Create new Test Rapport
2nd-factor/docs pull request #32
Opened 2021-01-13 20:19 UTC by yor101

Zoals besproken maandag avond zou ik een inleiding en een stukje over strategie schrijven

2021-01-14 18:41 UTC, exZell11 requested changes
opmerkingen geplaatst

2021-01-14 18:41 UTC, exZell11 commented on TestRapport.md
> +Bij de big bang strategie worden eerst individuele modules getest en vervolgens als een groot geheel.
```suggestion
Bij de big bang strategie worden eerst individuele modules getest en vervolgens als een groot geheel. 
```
uniform zijn en hier ook Big-Bang schrijven

2021-01-14 18:41 UTC, exZell11 commented on TestRapport.md
> +Bij de big bang strategie worden eerst individuele modules getest en vervolgens als een groot geheel.
```suggestion
Bij de big bang strategie worden eerst individuele modules getest en vervolgens als een groot geheel. 
```

uniform zijn en hier ook Big-Bang schrijven

2021-01-14 18:41 UTC, exZell11 commented on TestRapport.md
> +Wij, 2nd-Factor hebben de Big bang strategie als leidraad gekozen. Dit doordat het product 2nd-Factor als geheel binnen de marges blijft om goed en volledig
```suggestion
Wij, 2nd-Factor hebben de Big bang strategie als leidraad gekozen. Dit doordat het product 2nd-Factor als geheel binnen de marges blijft om goed en volledig 
```

Is het niet ook omdat het een relatief klein project is dat in 1x wordt opgeleverd?

2021-01-18 17:04 UTC, yor101 commented on TestRapport.md
> +Bij de big bang strategie worden eerst individuele modules getest en vervolgens als een groot geheel.
Ik heb de inleiding en Strategie aangepast. Zie mijn laatste commit

2021-01-18 18:40 UTC, exZell11 approved these changes

2021-01-19 18:32 UTC, RonaldVanDenBurg approved these changes
duim

2021-01-19 18:47 UTC, merged